name: Fetch JSON gh API Data

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
      - name: Wait for 5 seconds
        run: sleep 5

      # Step 1: Checkout 代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: 设置 Python 环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML tencentcloud-sdk-python-tts tencentcloud-sdk-python-aai

      # Step 4: 运行 Python 脚本
      - name: Run the script to fetch API data
        run: |
          python ankicard.py --API_KEY ${{ secrets.API_KEY }} --START_ALPHA_LIST g,h

      # Step 5: 提交结果到仓库（如果脚本生成新的文件）
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin master
          git add .
          git commit -m "Update data from API"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 用于授权推送更改

      # Step 6: 重新触发工作流
      - name: Re-run workflow
        if: success()  # 只有前面的步骤成功才会重新触发
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/Fetch_json_gh.yml/dispatches \
            -d '{"ref":"${{ github.ref }}"}'