name: Run Python Script to Fetch API Data

on:
  push:
    branches:
      - master  # 仅在向 main 分支推送代码时运行
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
      # Step 1: Checkout 代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: 设置 Python 环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: 运行 Python 脚本
      - name: Run the script to fetch API data
        run: |
          python main.py  # 替换为你的脚本文件名

      # Step 5: 提交结果到仓库（如果脚本生成新的文件）
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update data from API"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 用于授权推送更改
